### ISSUE TITLE
Navigation bar component

### ISSUE THREAD

**Issue by chartgerink** [libscie/dev.researchequals.com#7]
## Initial scope

- [x] Responsive design
- [x] Contains actions over pages
- [x] Overlay on the bottom of the page
- [x] Disappears on intersecting with footer

<details>
<summary>Design exploration</summary>
Our navigation bar will be heavily inspired by [Proof news](https://www.proofnews.org/). 

![Image](https://github.com/libscie/dev.researchequals.com/assets/2946344/2149a02f-d25b-4f3a-a215-a9aa024dbbd0)

The navigation bar is an overlay, instead of a static part of the page. This increases effective page real estate for the web application. It also allows for it to be available from any point of the page.

It is placed at the bottom as this is easily accessible from mobile, plus it feels modern (at this time). 

The mobile version reduces the navigation bar to a button, which can be expanded to get common actions within immediate reach.

![Image](https://github.com/libscie/dev.researchequals.com/assets/2946344/34299b3c-611c-4e2f-9a65-91963b9e8232)

I was able to semi-reproduce it using the original website.

<details>

```html
<header className='gh-navigation'>
        <div className='gh-navigation-inner'>
        <div className="gh-navigation-brand">
            <button className="gh-search gh-icon-button" aria-label="Search this site" data-ghost-search="">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" width="20" height="20"><path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg></button>            <button className="gh-burger gh-icon-button">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256"><path d="M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128ZM40,72H216a8,8,0,0,0,0-16H40a8,8,0,0,0,0,16ZM216,184H40a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16Z"></path></svg>                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256"><path d="M205.66,194.34a8,8,0,0,1-11.32,11.32L128,139.31,61.66,205.66a8,8,0,0,1-11.32-11.32L116.69,128,50.34,61.66A8,8,0,0,1,61.66,50.34L128,116.69l66.34-66.35a8,8,0,0,1,11.32,11.32L139.31,128Z"></path></svg>            </button>
        </div>
          <nav className='gh-navigation-menu'>
            <ul className='nav'>
              <li>
                <Link to={routes.home()}>Home</Link>
              </li>
              <li>
                <Link to={routes.home()}>Home</Link>
              </li>
            </ul>
          </nav>
          <div className="gh-navigation-members">
                                <a href="#/portal/signup" data-portal="signup" className="gh-portal-close">Join our mailing list</a>
                    <a className="gh-button gh-navigation-donate-button" href="/donate">Donate</a>
                </div>
        </div>
      </header>
```

```css

.gh-navigation {
	bottom: max(4vmin,40px);
	color: var(--color-foreground);
	font-size: var(--font-size-body);
	left: 50%;
	max-width: var(--container-width);
	padding: 0 max(4vmin,40px);
	position: fixed;
	transform: translateX(-50%);
	-webkit-user-select: none;
	-moz-user-select: none;
	user-select: none;
	width: 100%;
	z-index: 2999999;
}

.gh-navigation-brand {
	grid-column-start: 2;
	line-height: 1;
}

.gh-navigation-inner {
	align-items: center;
	-webkit-backdrop-filter: blur(24px);
	backdrop-filter: blur(24px);
	background-color: var(--color-background-navigation);
	border-radius: 9999px;
	box-shadow: var(--shadow);
	color: var(--color-foreground-navigation);
	-moz-column-gap: 24px;
	column-gap: 24px;
	display: inline-grid;
	font-weight: var(--font-weight-body-semibold);
	grid-auto-flow: row dense;
	grid-template-columns: 1fr auto auto;
	height: 100%;
	padding: .75em .75em .75em 2em;
	transition: background-color .2s ease-in;
  width: 100%;
}

.gh-navigation-menu {
	align-items: center;
	display: flex;
	gap: 24px;
}

.gh-navigation .nav {
	align-items: center;
	display: inline-flex;
	gap: 28px;
	list-style: none;
	margin: 0;
	padding: 0;
	white-space: nowrap;
}

.gh-viewport {
	display: flex;
	flex-direction: column;
	min-height: 100vh;
	position: relative;
}

.gh-navigation-actions {
	align-items: center;
	display: flex;
	gap: 24px;
	justify-content: flex-end;
}

:root {
	--color-white: #fff;
	--color-black: #000;
	--color-foreground: #0c0a55;
	--color-foreground-subtle: rgba(12,10,85,.7);
	--color-foreground-secondary: #d9f;
	--color-foreground-navigation: #0c0a55;
	--color-background: #f8f5ff;
	--color-background-elevated: #fff;
	--color-background-recessed: rgba(12,10,85,.08);
	--color-background-navigation: hsla(0,0%,100%,.8);
	--color-background-footer: #0c0a55;
	--color-border: rgba(12,10,85,.08);
	--color-dark-border: rgba(12,10,85,.5);
	--shadow: 0 12px 12px rgba(0,0,0,.04);
	--font-body: "Inter",sans-serif;
	--font-heading: "Insitu","Inter",sans-serif;
	--font-mono: monospace;
	--font-size-heading-smaller: 5.5rem;
	--font-size-heading: clamp(5rem,2.5vw + 3rem,6.5rem);
	--font-size-heading-2: clamp(2.5rem,2.5vw + 2rem,4.5rem);
	--font-size-body-smaller: 1.3rem;
	--font-size-body: 1.65rem;
	--font-size-body-larger: 2rem;
	--font-weight-body: 400;
	--font-weight-body-semibold: 500;
	--font-weight-body-bold: 800;
	--font-weight-heading: 300;
	--font-weight-heading-2: 600;
	--container-width: 1320px;
	--container-gap: clamp(24px,1.7032rem + 1.9355vw,48px);
	--grid-gap: 64px;
}

*, ::after, ::before {
	box-sizing: border-box;
}

.gh-navigation-brand {
	grid-column-start: 2;
	line-height: 1;
}
@media (max-width: 800px) {
.gh-navigation {
	width: auto;
}

.gh-navigation:not(.is-open) .gh-navigation-inner {
	align-items: center;
	display: flex;
	height: 64px;
	justify-content: center;
	padding: 0;
	width: 64px;
}

.gh-navigation .gh-navigation-inner {
	grid-template-columns: 1fr;
	grid-template-rows: auto 1fr auto;
}
.gh-navigation .gh-navigation-brand {
	align-items: center;
	display: grid;
	grid-column-start: 1;
	grid-template-columns: 1fr auto auto;
	height: 42px;
}

.gh-navigation .gh-navigation-menu {
	transform: translateY(0);
	transition: none;
}
.gh-navigation .gh-navigation-actions, .gh-navigation .gh-navigation-menu {
	justify-content: center;
	opacity: 0;
	position: fixed;
	visibility: hidden;
}

.gh-navigation .nav {
	align-items: center;
	gap: 20px;
	line-height: 1.4;
}

}

```

</details>
</details>
